version: "3"

services:
  db:
    build: ./mysql
    image: ktor3_mysql
    volumes:
      - mysql-volume:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: passj
      MYSQL_DATABASE: db_test
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-volume:
    driver: local
