version: "3"

services:
  db:
    build: ./mysql
    image: ktor3_mysql
    volumes:
      - mysql-volume:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: jpass
      MYSQL_DATABASE: db_test
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

volumes:
  mysql-volume:
    driver: local
